### ISSUE TITLE
links are not generated

### ISSUE THREAD

**Issue by pokyah** [SxDx/startpage#2]
Hi @SxDx ,

I try to implement my own version of your nice startpage. I've followed the instructions you provide in your README.md and edited my _config.yml file, but Jekyll does not generate the links in my index.html file which always remains empty. I'm quite new to jekyll and I don't really understand what is wrong in my config... 

You can have a look on my fork right [here](https://github.com/pokyah/startpage). 

I guess something goes wrong while parsing the /_data/bookmars.yml file but I can't figure out what exactly...

Any help would be greatly appreciated.

Thanks

**Comment by SxDx** [comment]
There was a typo in the Readme, I have fixed it here: https://github.com/SxDx/startpage/commit/466448813540e9b90bed5df87ccc97d7ce02dfee. 

book**s**marks.yml should be **booksmarks.yml**

**Comment by pokyah** [comment]
Aw ! Thanks @SxDx ! Obvious ... once you know it !
